spring:
  datasource:
    url:
    driver-class-name:
    username:
    password:
  jpa:
    hibernate:
      ddl-auto:
    database:
    show-sql:

springdoc:
  swagger-ui:
    path:

admin-options:
  email:
  password:
  firstName:
  lastName:

jwt-token-options:
  jwtExpirationMs:
  secret: 
